/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as PublicLayoutRouteRouteImport } from './routes/_publicLayout/route'
import { Route as HomeLayoutRouteRouteImport } from './routes/_homeLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeLayoutTransactionIndexRouteImport } from './routes/_homeLayout/transaction/index'
import { Route as HomeLayoutProfileIndexRouteImport } from './routes/_homeLayout/profile/index'
import { Route as HomeLayoutDashboardIndexRouteImport } from './routes/_homeLayout/dashboard/index'
import { Route as PublicLayoutAuthRegisterRouteImport } from './routes/_publicLayout/auth/register'
import { Route as PublicLayoutAuthLoginRouteImport } from './routes/_publicLayout/auth/login'
import { Route as HomeLayoutProfileEditRouteImport } from './routes/_homeLayout/profile/edit'
import { Route as HomeLayoutProfileChangePasswordRouteImport } from './routes/_homeLayout/profile/change-password'
import { Route as HomeLayoutTransactionAddIndexRouteImport } from './routes/_homeLayout/transaction/add/index'
import { Route as HomeLayoutSettingsNotificationsIndexRouteImport } from './routes/_homeLayout/settings/notifications/index'
import { Route as HomeLayoutSettingsCategoryIndexRouteImport } from './routes/_homeLayout/settings/category/index'
import { Route as HomeLayoutSettingsCategoryRuleRouteImport } from './routes/_homeLayout/settings/category/rule'

const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRouteRoute = PublicLayoutRouteRouteImport.update({
  id: '/_publicLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLayoutRouteRoute = HomeLayoutRouteRouteImport.update({
  id: '/_homeLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLayoutTransactionIndexRoute =
  HomeLayoutTransactionIndexRouteImport.update({
    id: '/transaction/',
    path: '/transaction/',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)
const HomeLayoutProfileIndexRoute = HomeLayoutProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => HomeLayoutRouteRoute,
} as any)
const HomeLayoutDashboardIndexRoute =
  HomeLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)
const PublicLayoutAuthRegisterRoute =
  PublicLayoutAuthRegisterRouteImport.update({
    id: '/auth/register',
    path: '/auth/register',
    getParentRoute: () => PublicLayoutRouteRoute,
  } as any)
const PublicLayoutAuthLoginRoute = PublicLayoutAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => PublicLayoutRouteRoute,
} as any)
const HomeLayoutProfileEditRoute = HomeLayoutProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => HomeLayoutRouteRoute,
} as any)
const HomeLayoutProfileChangePasswordRoute =
  HomeLayoutProfileChangePasswordRouteImport.update({
    id: '/profile/change-password',
    path: '/profile/change-password',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)
const HomeLayoutTransactionAddIndexRoute =
  HomeLayoutTransactionAddIndexRouteImport.update({
    id: '/transaction/add/',
    path: '/transaction/add/',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)
const HomeLayoutSettingsNotificationsIndexRoute =
  HomeLayoutSettingsNotificationsIndexRouteImport.update({
    id: '/settings/notifications/',
    path: '/settings/notifications/',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)
const HomeLayoutSettingsCategoryIndexRoute =
  HomeLayoutSettingsCategoryIndexRouteImport.update({
    id: '/settings/category/',
    path: '/settings/category/',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)
const HomeLayoutSettingsCategoryRuleRoute =
  HomeLayoutSettingsCategoryRuleRouteImport.update({
    id: '/settings/category/rule',
    path: '/settings/category/rule',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/forbidden': typeof ForbiddenRoute
  '/profile/change-password': typeof HomeLayoutProfileChangePasswordRoute
  '/profile/edit': typeof HomeLayoutProfileEditRoute
  '/auth/login': typeof PublicLayoutAuthLoginRoute
  '/auth/register': typeof PublicLayoutAuthRegisterRoute
  '/dashboard/': typeof HomeLayoutDashboardIndexRoute
  '/profile/': typeof HomeLayoutProfileIndexRoute
  '/transaction/': typeof HomeLayoutTransactionIndexRoute
  '/settings/category/rule': typeof HomeLayoutSettingsCategoryRuleRoute
  '/settings/category/': typeof HomeLayoutSettingsCategoryIndexRoute
  '/settings/notifications/': typeof HomeLayoutSettingsNotificationsIndexRoute
  '/transaction/add/': typeof HomeLayoutTransactionAddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/forbidden': typeof ForbiddenRoute
  '/profile/change-password': typeof HomeLayoutProfileChangePasswordRoute
  '/profile/edit': typeof HomeLayoutProfileEditRoute
  '/auth/login': typeof PublicLayoutAuthLoginRoute
  '/auth/register': typeof PublicLayoutAuthRegisterRoute
  '/dashboard': typeof HomeLayoutDashboardIndexRoute
  '/profile': typeof HomeLayoutProfileIndexRoute
  '/transaction': typeof HomeLayoutTransactionIndexRoute
  '/settings/category/rule': typeof HomeLayoutSettingsCategoryRuleRoute
  '/settings/category': typeof HomeLayoutSettingsCategoryIndexRoute
  '/settings/notifications': typeof HomeLayoutSettingsNotificationsIndexRoute
  '/transaction/add': typeof HomeLayoutTransactionAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_homeLayout': typeof HomeLayoutRouteRouteWithChildren
  '/_publicLayout': typeof PublicLayoutRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/forbidden': typeof ForbiddenRoute
  '/_homeLayout/profile/change-password': typeof HomeLayoutProfileChangePasswordRoute
  '/_homeLayout/profile/edit': typeof HomeLayoutProfileEditRoute
  '/_publicLayout/auth/login': typeof PublicLayoutAuthLoginRoute
  '/_publicLayout/auth/register': typeof PublicLayoutAuthRegisterRoute
  '/_homeLayout/dashboard/': typeof HomeLayoutDashboardIndexRoute
  '/_homeLayout/profile/': typeof HomeLayoutProfileIndexRoute
  '/_homeLayout/transaction/': typeof HomeLayoutTransactionIndexRoute
  '/_homeLayout/settings/category/rule': typeof HomeLayoutSettingsCategoryRuleRoute
  '/_homeLayout/settings/category/': typeof HomeLayoutSettingsCategoryIndexRoute
  '/_homeLayout/settings/notifications/': typeof HomeLayoutSettingsNotificationsIndexRoute
  '/_homeLayout/transaction/add/': typeof HomeLayoutTransactionAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/forbidden'
    | '/profile/change-password'
    | '/profile/edit'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/'
    | '/profile/'
    | '/transaction/'
    | '/settings/category/rule'
    | '/settings/category/'
    | '/settings/notifications/'
    | '/transaction/add/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/forbidden'
    | '/profile/change-password'
    | '/profile/edit'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard'
    | '/profile'
    | '/transaction'
    | '/settings/category/rule'
    | '/settings/category'
    | '/settings/notifications'
    | '/transaction/add'
  id:
    | '__root__'
    | '/'
    | '/_homeLayout'
    | '/_publicLayout'
    | '/error'
    | '/forbidden'
    | '/_homeLayout/profile/change-password'
    | '/_homeLayout/profile/edit'
    | '/_publicLayout/auth/login'
    | '/_publicLayout/auth/register'
    | '/_homeLayout/dashboard/'
    | '/_homeLayout/profile/'
    | '/_homeLayout/transaction/'
    | '/_homeLayout/settings/category/rule'
    | '/_homeLayout/settings/category/'
    | '/_homeLayout/settings/notifications/'
    | '/_homeLayout/transaction/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeLayoutRouteRoute: typeof HomeLayoutRouteRouteWithChildren
  PublicLayoutRouteRoute: typeof PublicLayoutRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  ForbiddenRoute: typeof ForbiddenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_publicLayout': {
      id: '/_publicLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homeLayout': {
      id: '/_homeLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homeLayout/transaction/': {
      id: '/_homeLayout/transaction/'
      path: '/transaction'
      fullPath: '/transaction/'
      preLoaderRoute: typeof HomeLayoutTransactionIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/profile/': {
      id: '/_homeLayout/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof HomeLayoutProfileIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/dashboard/': {
      id: '/_homeLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof HomeLayoutDashboardIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_publicLayout/auth/register': {
      id: '/_publicLayout/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof PublicLayoutAuthRegisterRouteImport
      parentRoute: typeof PublicLayoutRouteRoute
    }
    '/_publicLayout/auth/login': {
      id: '/_publicLayout/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicLayoutAuthLoginRouteImport
      parentRoute: typeof PublicLayoutRouteRoute
    }
    '/_homeLayout/profile/edit': {
      id: '/_homeLayout/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof HomeLayoutProfileEditRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/profile/change-password': {
      id: '/_homeLayout/profile/change-password'
      path: '/profile/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof HomeLayoutProfileChangePasswordRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/transaction/add/': {
      id: '/_homeLayout/transaction/add/'
      path: '/transaction/add'
      fullPath: '/transaction/add/'
      preLoaderRoute: typeof HomeLayoutTransactionAddIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/settings/notifications/': {
      id: '/_homeLayout/settings/notifications/'
      path: '/settings/notifications'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof HomeLayoutSettingsNotificationsIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/settings/category/': {
      id: '/_homeLayout/settings/category/'
      path: '/settings/category'
      fullPath: '/settings/category/'
      preLoaderRoute: typeof HomeLayoutSettingsCategoryIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/settings/category/rule': {
      id: '/_homeLayout/settings/category/rule'
      path: '/settings/category/rule'
      fullPath: '/settings/category/rule'
      preLoaderRoute: typeof HomeLayoutSettingsCategoryRuleRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
  }
}

interface HomeLayoutRouteRouteChildren {
  HomeLayoutProfileChangePasswordRoute: typeof HomeLayoutProfileChangePasswordRoute
  HomeLayoutProfileEditRoute: typeof HomeLayoutProfileEditRoute
  HomeLayoutDashboardIndexRoute: typeof HomeLayoutDashboardIndexRoute
  HomeLayoutProfileIndexRoute: typeof HomeLayoutProfileIndexRoute
  HomeLayoutTransactionIndexRoute: typeof HomeLayoutTransactionIndexRoute
  HomeLayoutSettingsCategoryRuleRoute: typeof HomeLayoutSettingsCategoryRuleRoute
  HomeLayoutSettingsCategoryIndexRoute: typeof HomeLayoutSettingsCategoryIndexRoute
  HomeLayoutSettingsNotificationsIndexRoute: typeof HomeLayoutSettingsNotificationsIndexRoute
  HomeLayoutTransactionAddIndexRoute: typeof HomeLayoutTransactionAddIndexRoute
}

const HomeLayoutRouteRouteChildren: HomeLayoutRouteRouteChildren = {
  HomeLayoutProfileChangePasswordRoute: HomeLayoutProfileChangePasswordRoute,
  HomeLayoutProfileEditRoute: HomeLayoutProfileEditRoute,
  HomeLayoutDashboardIndexRoute: HomeLayoutDashboardIndexRoute,
  HomeLayoutProfileIndexRoute: HomeLayoutProfileIndexRoute,
  HomeLayoutTransactionIndexRoute: HomeLayoutTransactionIndexRoute,
  HomeLayoutSettingsCategoryRuleRoute: HomeLayoutSettingsCategoryRuleRoute,
  HomeLayoutSettingsCategoryIndexRoute: HomeLayoutSettingsCategoryIndexRoute,
  HomeLayoutSettingsNotificationsIndexRoute:
    HomeLayoutSettingsNotificationsIndexRoute,
  HomeLayoutTransactionAddIndexRoute: HomeLayoutTransactionAddIndexRoute,
}

const HomeLayoutRouteRouteWithChildren = HomeLayoutRouteRoute._addFileChildren(
  HomeLayoutRouteRouteChildren,
)

interface PublicLayoutRouteRouteChildren {
  PublicLayoutAuthLoginRoute: typeof PublicLayoutAuthLoginRoute
  PublicLayoutAuthRegisterRoute: typeof PublicLayoutAuthRegisterRoute
}

const PublicLayoutRouteRouteChildren: PublicLayoutRouteRouteChildren = {
  PublicLayoutAuthLoginRoute: PublicLayoutAuthLoginRoute,
  PublicLayoutAuthRegisterRoute: PublicLayoutAuthRegisterRoute,
}

const PublicLayoutRouteRouteWithChildren =
  PublicLayoutRouteRoute._addFileChildren(PublicLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeLayoutRouteRoute: HomeLayoutRouteRouteWithChildren,
  PublicLayoutRouteRoute: PublicLayoutRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
  ForbiddenRoute: ForbiddenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
