/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicLayoutRouteRouteImport } from './routes/_publicLayout/route'
import { Route as HomeLayoutRouteRouteImport } from './routes/_homeLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeLayoutTransactionIndexRouteImport } from './routes/_homeLayout/transaction/index'
import { Route as HomeLayoutSettingsIndexRouteImport } from './routes/_homeLayout/settings/index'
import { Route as HomeLayoutProfileIndexRouteImport } from './routes/_homeLayout/profile/index'
import { Route as HomeLayoutDashboardIndexRouteImport } from './routes/_homeLayout/dashboard/index'
import { Route as HomeLayoutProfileEditRouteImport } from './routes/_homeLayout/profile/edit'
import { Route as HomeLayoutProfileChangePasswordRouteImport } from './routes/_homeLayout/profile/change-password'
import { Route as PublicLayoutAuthRegisterIndexRouteImport } from './routes/_publicLayout/auth/register/index'
import { Route as PublicLayoutAuthLoginIndexRouteImport } from './routes/_publicLayout/auth/login/index'
import { Route as HomeLayoutTransactionAddIndexRouteImport } from './routes/_homeLayout/transaction/add/index'
import { Route as HomeLayoutSettingsNotificationsIndexRouteImport } from './routes/_homeLayout/settings/notifications/index'
import { Route as HomeLayoutSettingsCategoryRuleIndexRouteImport } from './routes/_homeLayout/settings/category-rule/index'
import { Route as HomeLayoutSettingsBudgetGoalsIndexRouteImport } from './routes/_homeLayout/settings/budget-goals/index'

const PublicLayoutRouteRoute = PublicLayoutRouteRouteImport.update({
  id: '/_publicLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLayoutRouteRoute = HomeLayoutRouteRouteImport.update({
  id: '/_homeLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLayoutTransactionIndexRoute =
  HomeLayoutTransactionIndexRouteImport.update({
    id: '/transaction/',
    path: '/transaction/',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)
const HomeLayoutSettingsIndexRoute = HomeLayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => HomeLayoutRouteRoute,
} as any)
const HomeLayoutProfileIndexRoute = HomeLayoutProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => HomeLayoutRouteRoute,
} as any)
const HomeLayoutDashboardIndexRoute =
  HomeLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)
const HomeLayoutProfileEditRoute = HomeLayoutProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => HomeLayoutRouteRoute,
} as any)
const HomeLayoutProfileChangePasswordRoute =
  HomeLayoutProfileChangePasswordRouteImport.update({
    id: '/profile/change-password',
    path: '/profile/change-password',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)
const PublicLayoutAuthRegisterIndexRoute =
  PublicLayoutAuthRegisterIndexRouteImport.update({
    id: '/auth/register/',
    path: '/auth/register/',
    getParentRoute: () => PublicLayoutRouteRoute,
  } as any)
const PublicLayoutAuthLoginIndexRoute =
  PublicLayoutAuthLoginIndexRouteImport.update({
    id: '/auth/login/',
    path: '/auth/login/',
    getParentRoute: () => PublicLayoutRouteRoute,
  } as any)
const HomeLayoutTransactionAddIndexRoute =
  HomeLayoutTransactionAddIndexRouteImport.update({
    id: '/transaction/add/',
    path: '/transaction/add/',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)
const HomeLayoutSettingsNotificationsIndexRoute =
  HomeLayoutSettingsNotificationsIndexRouteImport.update({
    id: '/settings/notifications/',
    path: '/settings/notifications/',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)
const HomeLayoutSettingsCategoryRuleIndexRoute =
  HomeLayoutSettingsCategoryRuleIndexRouteImport.update({
    id: '/settings/category-rule/',
    path: '/settings/category-rule/',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)
const HomeLayoutSettingsBudgetGoalsIndexRoute =
  HomeLayoutSettingsBudgetGoalsIndexRouteImport.update({
    id: '/settings/budget-goals/',
    path: '/settings/budget-goals/',
    getParentRoute: () => HomeLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile/change-password': typeof HomeLayoutProfileChangePasswordRoute
  '/profile/edit': typeof HomeLayoutProfileEditRoute
  '/dashboard/': typeof HomeLayoutDashboardIndexRoute
  '/profile/': typeof HomeLayoutProfileIndexRoute
  '/settings/': typeof HomeLayoutSettingsIndexRoute
  '/transaction/': typeof HomeLayoutTransactionIndexRoute
  '/settings/budget-goals/': typeof HomeLayoutSettingsBudgetGoalsIndexRoute
  '/settings/category-rule/': typeof HomeLayoutSettingsCategoryRuleIndexRoute
  '/settings/notifications/': typeof HomeLayoutSettingsNotificationsIndexRoute
  '/transaction/add/': typeof HomeLayoutTransactionAddIndexRoute
  '/auth/login/': typeof PublicLayoutAuthLoginIndexRoute
  '/auth/register/': typeof PublicLayoutAuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile/change-password': typeof HomeLayoutProfileChangePasswordRoute
  '/profile/edit': typeof HomeLayoutProfileEditRoute
  '/dashboard': typeof HomeLayoutDashboardIndexRoute
  '/profile': typeof HomeLayoutProfileIndexRoute
  '/settings': typeof HomeLayoutSettingsIndexRoute
  '/transaction': typeof HomeLayoutTransactionIndexRoute
  '/settings/budget-goals': typeof HomeLayoutSettingsBudgetGoalsIndexRoute
  '/settings/category-rule': typeof HomeLayoutSettingsCategoryRuleIndexRoute
  '/settings/notifications': typeof HomeLayoutSettingsNotificationsIndexRoute
  '/transaction/add': typeof HomeLayoutTransactionAddIndexRoute
  '/auth/login': typeof PublicLayoutAuthLoginIndexRoute
  '/auth/register': typeof PublicLayoutAuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_homeLayout': typeof HomeLayoutRouteRouteWithChildren
  '/_publicLayout': typeof PublicLayoutRouteRouteWithChildren
  '/_homeLayout/profile/change-password': typeof HomeLayoutProfileChangePasswordRoute
  '/_homeLayout/profile/edit': typeof HomeLayoutProfileEditRoute
  '/_homeLayout/dashboard/': typeof HomeLayoutDashboardIndexRoute
  '/_homeLayout/profile/': typeof HomeLayoutProfileIndexRoute
  '/_homeLayout/settings/': typeof HomeLayoutSettingsIndexRoute
  '/_homeLayout/transaction/': typeof HomeLayoutTransactionIndexRoute
  '/_homeLayout/settings/budget-goals/': typeof HomeLayoutSettingsBudgetGoalsIndexRoute
  '/_homeLayout/settings/category-rule/': typeof HomeLayoutSettingsCategoryRuleIndexRoute
  '/_homeLayout/settings/notifications/': typeof HomeLayoutSettingsNotificationsIndexRoute
  '/_homeLayout/transaction/add/': typeof HomeLayoutTransactionAddIndexRoute
  '/_publicLayout/auth/login/': typeof PublicLayoutAuthLoginIndexRoute
  '/_publicLayout/auth/register/': typeof PublicLayoutAuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile/change-password'
    | '/profile/edit'
    | '/dashboard/'
    | '/profile/'
    | '/settings/'
    | '/transaction/'
    | '/settings/budget-goals/'
    | '/settings/category-rule/'
    | '/settings/notifications/'
    | '/transaction/add/'
    | '/auth/login/'
    | '/auth/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile/change-password'
    | '/profile/edit'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/transaction'
    | '/settings/budget-goals'
    | '/settings/category-rule'
    | '/settings/notifications'
    | '/transaction/add'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/_homeLayout'
    | '/_publicLayout'
    | '/_homeLayout/profile/change-password'
    | '/_homeLayout/profile/edit'
    | '/_homeLayout/dashboard/'
    | '/_homeLayout/profile/'
    | '/_homeLayout/settings/'
    | '/_homeLayout/transaction/'
    | '/_homeLayout/settings/budget-goals/'
    | '/_homeLayout/settings/category-rule/'
    | '/_homeLayout/settings/notifications/'
    | '/_homeLayout/transaction/add/'
    | '/_publicLayout/auth/login/'
    | '/_publicLayout/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeLayoutRouteRoute: typeof HomeLayoutRouteRouteWithChildren
  PublicLayoutRouteRoute: typeof PublicLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_publicLayout': {
      id: '/_publicLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homeLayout': {
      id: '/_homeLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homeLayout/transaction/': {
      id: '/_homeLayout/transaction/'
      path: '/transaction'
      fullPath: '/transaction/'
      preLoaderRoute: typeof HomeLayoutTransactionIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/settings/': {
      id: '/_homeLayout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof HomeLayoutSettingsIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/profile/': {
      id: '/_homeLayout/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof HomeLayoutProfileIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/dashboard/': {
      id: '/_homeLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof HomeLayoutDashboardIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/profile/edit': {
      id: '/_homeLayout/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof HomeLayoutProfileEditRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/profile/change-password': {
      id: '/_homeLayout/profile/change-password'
      path: '/profile/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof HomeLayoutProfileChangePasswordRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_publicLayout/auth/register/': {
      id: '/_publicLayout/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof PublicLayoutAuthRegisterIndexRouteImport
      parentRoute: typeof PublicLayoutRouteRoute
    }
    '/_publicLayout/auth/login/': {
      id: '/_publicLayout/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof PublicLayoutAuthLoginIndexRouteImport
      parentRoute: typeof PublicLayoutRouteRoute
    }
    '/_homeLayout/transaction/add/': {
      id: '/_homeLayout/transaction/add/'
      path: '/transaction/add'
      fullPath: '/transaction/add/'
      preLoaderRoute: typeof HomeLayoutTransactionAddIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/settings/notifications/': {
      id: '/_homeLayout/settings/notifications/'
      path: '/settings/notifications'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof HomeLayoutSettingsNotificationsIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/settings/category-rule/': {
      id: '/_homeLayout/settings/category-rule/'
      path: '/settings/category-rule'
      fullPath: '/settings/category-rule/'
      preLoaderRoute: typeof HomeLayoutSettingsCategoryRuleIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
    '/_homeLayout/settings/budget-goals/': {
      id: '/_homeLayout/settings/budget-goals/'
      path: '/settings/budget-goals'
      fullPath: '/settings/budget-goals/'
      preLoaderRoute: typeof HomeLayoutSettingsBudgetGoalsIndexRouteImport
      parentRoute: typeof HomeLayoutRouteRoute
    }
  }
}

interface HomeLayoutRouteRouteChildren {
  HomeLayoutProfileChangePasswordRoute: typeof HomeLayoutProfileChangePasswordRoute
  HomeLayoutProfileEditRoute: typeof HomeLayoutProfileEditRoute
  HomeLayoutDashboardIndexRoute: typeof HomeLayoutDashboardIndexRoute
  HomeLayoutProfileIndexRoute: typeof HomeLayoutProfileIndexRoute
  HomeLayoutSettingsIndexRoute: typeof HomeLayoutSettingsIndexRoute
  HomeLayoutTransactionIndexRoute: typeof HomeLayoutTransactionIndexRoute
  HomeLayoutSettingsBudgetGoalsIndexRoute: typeof HomeLayoutSettingsBudgetGoalsIndexRoute
  HomeLayoutSettingsCategoryRuleIndexRoute: typeof HomeLayoutSettingsCategoryRuleIndexRoute
  HomeLayoutSettingsNotificationsIndexRoute: typeof HomeLayoutSettingsNotificationsIndexRoute
  HomeLayoutTransactionAddIndexRoute: typeof HomeLayoutTransactionAddIndexRoute
}

const HomeLayoutRouteRouteChildren: HomeLayoutRouteRouteChildren = {
  HomeLayoutProfileChangePasswordRoute: HomeLayoutProfileChangePasswordRoute,
  HomeLayoutProfileEditRoute: HomeLayoutProfileEditRoute,
  HomeLayoutDashboardIndexRoute: HomeLayoutDashboardIndexRoute,
  HomeLayoutProfileIndexRoute: HomeLayoutProfileIndexRoute,
  HomeLayoutSettingsIndexRoute: HomeLayoutSettingsIndexRoute,
  HomeLayoutTransactionIndexRoute: HomeLayoutTransactionIndexRoute,
  HomeLayoutSettingsBudgetGoalsIndexRoute:
    HomeLayoutSettingsBudgetGoalsIndexRoute,
  HomeLayoutSettingsCategoryRuleIndexRoute:
    HomeLayoutSettingsCategoryRuleIndexRoute,
  HomeLayoutSettingsNotificationsIndexRoute:
    HomeLayoutSettingsNotificationsIndexRoute,
  HomeLayoutTransactionAddIndexRoute: HomeLayoutTransactionAddIndexRoute,
}

const HomeLayoutRouteRouteWithChildren = HomeLayoutRouteRoute._addFileChildren(
  HomeLayoutRouteRouteChildren,
)

interface PublicLayoutRouteRouteChildren {
  PublicLayoutAuthLoginIndexRoute: typeof PublicLayoutAuthLoginIndexRoute
  PublicLayoutAuthRegisterIndexRoute: typeof PublicLayoutAuthRegisterIndexRoute
}

const PublicLayoutRouteRouteChildren: PublicLayoutRouteRouteChildren = {
  PublicLayoutAuthLoginIndexRoute: PublicLayoutAuthLoginIndexRoute,
  PublicLayoutAuthRegisterIndexRoute: PublicLayoutAuthRegisterIndexRoute,
}

const PublicLayoutRouteRouteWithChildren =
  PublicLayoutRouteRoute._addFileChildren(PublicLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeLayoutRouteRoute: HomeLayoutRouteRouteWithChildren,
  PublicLayoutRouteRoute: PublicLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
